/**
 * @module @morkg/aleph
 * @description Temporal cryptography and absolute unique value generator based on AES-256 and UUIDv7.
 */

import crypto from "node:crypto";

/**
 * Fixed size of the cryptographic block generated by the ciphered UUIDv7.
 * Math: 32 chars (IV) + 96 chars (UUIDv7 36 bytes padded to 48 bytes in hex) = 128
 */
const UUID7_SIZE_CRIPTO = 128;

/**
 * Converts a number to a hexadecimal string with a specified length.
 * @param value The number to convert.
 * @param length The desired length of the resulting hexadecimal string.
 * @returns The hexadecimal string.
 */

const toHex = (value: number, length: number): string =>
  value.toString(16).padStart(length, "0");

/**
 * Generates a new UUIDv7.
 * @returns The generated UUIDv7.
 * @internal
 */
const uuidv7 = (): string => {
  const timestamp = BigInt(Date.now()) & 0xffffffffffffn;
  const random = crypto.randomBytes(10);

  const timeLow = Number(timestamp & 0xffffffffn);
  const timeMid = Number((timestamp >> 32n) & 0xffffn);
  const timeHighAndVersion = 0x7000 | (random.readUInt16BE(0) & 0x0fff);
  const clockSeqHiAndReserved = 0x80 | (random[2] & 0x3f);
  const clockSeqLow = random[3];
  const node = random.subarray(4, 10);

  return `${toHex(timeLow, 8)}-${toHex(timeMid, 4)}-${toHex(
    timeHighAndVersion,
    4,
  )}-${toHex(clockSeqHiAndReserved, 2)}${toHex(clockSeqLow, 2)}-${node.toString(
    "hex",
  )}`;
};

/**
 * Internal primary encryption function (AES-256-CBC).
 * @internal
 */
const e = (text: string, secret: string): string => {
  const r = crypto
    .createHash("sha256")
    .update(secret)
    .digest("base64")
    .substring(0, 32);
  const s = crypto.randomBytes(16);
  const a = crypto.createCipheriv("aes-256-cbc", r, s);
  let c = a.update(text, "utf8", "hex") + a.final("hex");
  return s.toString("hex") + c;
};

/**
 * Internal primary decryption function (AES-256-CBC).
 * @internal
 */
const d = (token: string, secret: string): string => {
  const r = crypto
    .createHash("sha256")
    .update(secret)
    .digest("base64")
    .substring(0, 32);
  const s = Buffer.from(token.substring(0, 32), "hex");
  const a = token.substring(32);
  const c = crypto.createDecipheriv("aes-256-cbc", r, s);
  return c.update(a, "hex", "utf8") + c.final("utf8");
};

/**
 * Generates a unique, time-based cryptographic token (Aleph Token).
 * Encapsulates the original content within a double layer of security using UUIDv7.
 * @param text - The content or payload that will be hidden inside the token.
 * @param secret - The master key (password) to protect the token.
 * @param expire - Optional expiration date or timestamp (milliseconds).
 * @returns A long hexadecimal string representing the generated token.
 */
export const encode = (
  text: string,
  secret: string,
  expire?: Date | number,
): string => {
  const timestamp = expire instanceof Date ? expire.getTime() : expire;
  const payload = timestamp ? `${text}[@EXP:${timestamp}]` : text;
  return ((uuid) => e(uuid, secret) + e(payload, uuid))(uuidv7());
};

/**
 * Decrypts an Aleph token to retrieve its original value.
 * @param token - The previously generated hexadecimal Aleph token.
 * @param secret - The master key (password) used during encryption.
 * @throws {Error} Throws an error if the token has expired.
 * @returns The original content in plain text (UTF-8).
 */
export const decode = (token: string, secret: string): string => {
  const decrypted = d(
    token.substring(UUID7_SIZE_CRIPTO),
    d(token.substring(0, UUID7_SIZE_CRIPTO), secret),
  );

  const expMatch = decrypted.match(/\[@EXP:(\d+)\]$/);

  if (expMatch) {
    const expirationTime = parseInt(expMatch[1], 10);
    if (Date.now() > expirationTime) {
      throw new Error("Token expired");
    }
    return decrypted.slice(0, -expMatch[0].length);
  }

  return decrypted;
};

/**
 * Extracts the exact creation date of an Aleph token.
 * @example
 * import { origin } from "@morkg/aleph";
 * * const birthDate = origin(token, "master_secret");
 * console.log(birthDate.toISOString());
 * @param token - The previously generated hexadecimal Aleph token.
 * @param secret - The master key (password) used during encryption.
 * @returns A JavaScript Date object representing when the token was born.
 */
export const origin = (token: string, secret: string): Date => {
  // 1. Decifra apenas a primeira parte do token para revelar o UUID original
  const uuid = d(token.substring(0, UUID7_SIZE_CRIPTO), secret);

  // 2. Extrai os primeiros 48 bits (os 8 chars do primeiro bloco + 4 do segundo)
  const hexTimestamp = uuid.substring(0, 8) + uuid.substring(9, 13);

  // 3. Converte de Hexadecimal para Decimal (Milissegundos)
  const timestampMs = parseInt(hexTimestamp, 16);

  // 4. Retorna um objeto Date real
  return new Date(timestampMs);
};

/**
 * Default Aleph library object.
 * Allows namespace imports: `import aleph from '@morkg/aleph'`.
 */
const aleph = {
  decode,
  encode,
  origin,
};

export default aleph;
