/**
 * @module @morkg/aleph
 * @description Temporal cryptography and absolute unique value generator based on AES-256 and UUIDv7.
 */

import crypto from "node:crypto";
import { v7 as uuidv7 } from "uuid";

/**
 * Fixed size of the cryptographic block generated by the ciphered UUIDv7.
 * Math: 32 chars (IV) + 96 chars (UUIDv7 36 bytes padded to 48 bytes in hex) = 128
 */
const UUID7_SIZE_CRIPTO = 128;

/**
 * Internal primary encryption function (AES-256-CBC).
 * @internal
 */
const e = (text: string, secret: string): string => {
  const r = crypto
    .createHash("sha256")
    .update(secret)
    .digest("base64")
    .substring(0, 32);
  const s = crypto.randomBytes(16);
  const a = crypto.createCipheriv("aes-256-cbc", r, s);
  let c = a.update(text, "utf8", "hex") + a.final("hex");
  return s.toString("hex") + c;
};

/**
 * Internal primary decryption function (AES-256-CBC).
 * @internal
 */
const d = (token: string, secret: string): string => {
  const r = crypto
    .createHash("sha256")
    .update(secret)
    .digest("base64")
    .substring(0, 32);
  const s = Buffer.from(token.substring(0, 32), "hex");
  const a = token.substring(32);
  const c = crypto.createDecipheriv("aes-256-cbc", r, s);
  return c.update(a, "hex", "utf8") + c.final("utf8");
};

/**
 * Generates a unique, time-based cryptographic token (Aleph Token).
 * Encapsulates the original content within a double layer of security using UUIDv7.
 * @param text - The content or payload that will be hidden inside the token.
 * @param secret - The master key (password) to protect the token.
 * @param expire - Optional expiration date or timestamp (milliseconds).
 * @returns A long hexadecimal string representing the generated token.
 */
export const encode = (
  text: string,
  secret: string,
  expire?: Date | number,
): string => {
  const timestamp = expire instanceof Date ? expire.getTime() : expire;
  const payload = timestamp ? `${text}[@EXP:${timestamp}]` : text;
  return ((uuid) => e(uuid, secret) + e(payload, uuid))(uuidv7());
};

/**
 * Decrypts an Aleph token to retrieve its original value.
 * @param token - The previously generated hexadecimal Aleph token.
 * @param secret - The master key (password) used during encryption.
 * @throws {Error} Throws an error if the token has expired.
 * @returns The original content in plain text (UTF-8).
 */
export const decode = (token: string, secret: string): string => {
  const decrypted = d(
    token.substring(UUID7_SIZE_CRIPTO),
    d(token.substring(0, UUID7_SIZE_CRIPTO), secret),
  );

  const expMatch = decrypted.match(/\[@EXP:(\d+)\]$/);

  if (expMatch) {
    const expirationTime = parseInt(expMatch[1], 10);
    if (Date.now() > expirationTime) {
      throw new Error("Token expired");
    }
    return decrypted.slice(0, -expMatch[0].length);
  }

  return decrypted;
};

/**
 * Default Aleph library object.
 * Allows namespace imports: `import aleph from '@morkg/aleph'`.
 */
const aleph = {
  decode,
  encode,
};

export default aleph;
